# This file was generated by GoReleaser. DO NOT EDIT.
cask "seshat" do
  name "seshat"
  desc "A lightweight TUI SQL client for PostgreSQL"
  homepage "https://github.com/tardanoir/seshat"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seshat"

  on_macos do
    on_intel do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_darwin_amd64.tar.gz"
      sha256 "98f625a1db84c30e232cef19bc003f32fdb573a5f7e9603c3ad85069a47f5a16"
    end
    on_arm do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_darwin_arm64.tar.gz"
      sha256 "1777abf3ca6133b112d1b3b4046f116df3a373fcd453029c30b269d57074d0dc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_linux_amd64.tar.gz"
      sha256 "bc12a97750f5ac9417699676b21fa339b894d27e6fcb54c16f1e9717d3873586"
    end
    on_arm do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_linux_arm64.tar.gz"
      sha256 "3c0228dd23e1096653e50917d06bbd277209fa997ff2b8529d655c3d6ac4cdb8"
    end
  end

  # No zap stanza required
end
