# This file was generated by GoReleaser. DO NOT EDIT.
cask "seshat" do
  name "seshat"
  desc "A lightweight TUI SQL client for PostgreSQL"
  homepage "https://github.com/tardanoir/seshat"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seshat"

  on_macos do
    on_intel do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_darwin_amd64.tar.gz"
      sha256 "42d72e6f2cc4ffd2f4d19380945fed5e567511a3f356c4d8f14fcfb5d89e91bd"
    end
    on_arm do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_darwin_arm64.tar.gz"
      sha256 "23495df2b8ddaba8bb3d6f27cb3920802ed9ea4187ac95771d185f9b8df74134"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_linux_amd64.tar.gz"
      sha256 "56b77f9802091d2a3d5fd3fc6833c1e7eeff10227614983aa2fe082a6d126aad"
    end
    on_arm do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_linux_arm64.tar.gz"
      sha256 "ae9587c52415efed383a2837b16af774311e1de2dca3b5673a24e06b881faf61"
    end
  end

  # No zap stanza required
end
