# This file was generated by GoReleaser. DO NOT EDIT.
cask "seshat" do
  name "seshat"
  desc "A lightweight TUI SQL client for PostgreSQL"
  homepage "https://github.com/tardanoir/seshat"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seshat"

  on_macos do
    on_intel do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_darwin_amd64.tar.gz"
      sha256 "71238e7485315d58b9c231a8c3cb534db975cb5d8c0e7d12c8f4ee7b68315942"
    end
    on_arm do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_darwin_arm64.tar.gz"
      sha256 "647e3b192efc2c6335312a16c32a94323d2cf40ce24b44b61dc8316ebd633996"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_linux_amd64.tar.gz"
      sha256 "63acd8e08d31354b48cf1e4294fb0b9b1323c94f2dc14fe7e35738ca1b21f024"
    end
    on_arm do
      url "https://github.com/tardanoir/seshat/releases/download/v#{version}/seshat_#{version}_linux_arm64.tar.gz"
      sha256 "0f881fc746028dff2dd05256b8866a3812b123c1e67b5c2a34c06385ee6dd264"
    end
  end

  # No zap stanza required
end
